### ISSUE TITLE
Error on line 61

### ISSUE THREAD

**Issue by SyntageCron** [SaltyGrandpa/salty_tokenizer#2]
Error running system event handling function for resource salty_tokenizer: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server.lua:61: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        server.lua:61: in function 'isTokenUnique'
        server.lua:84: in function 'generateToken'
        server.lua:93: in function 'getObfuscatedEvent'
        server.lua:115: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>

**Comment by chandanroksjsr** [comment]
did you find any solution for this??

**Comment by SaltyGrandpa** [comment]
Resolved in #3
